<?php

namespace ContainerRjUlOZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerforgotPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a9y0Qxc.App\Controller\ProfileController::forgotPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a9y0Qxc.App\\Controller\\ProfileController::forgotPassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenGenerator' => ['privates', 'security.csrf.token_generator', 'getSecurity_Csrf_TokenGeneratorService', false],
            'smsService' => ['privates', 'App\\Service\\SmsService', 'getSmsServiceService', true],
        ], [
            'entityManager' => '?',
            'tokenGenerator' => '?',
            'smsService' => 'App\\Service\\SmsService',
        ]))->withContext('App\\Controller\\ProfileController::forgotPassword()', $container);
    }
}
