<?php

namespace ContainerRjUlOZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerresetPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A84gqGd.App\Controller\ProfileController::resetPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.A84gqGd'] ?? $container->load('get_ServiceLocator_A84gqGdService'));

        if (isset($container->privates['.service_locator.A84gqGd.App\\Controller\\ProfileController::resetPassword()'])) {
            return $container->privates['.service_locator.A84gqGd.App\\Controller\\ProfileController::resetPassword()'];
        }

        return $container->privates['.service_locator.A84gqGd.App\\Controller\\ProfileController::resetPassword()'] = $a->withContext('App\\Controller\\ProfileController::resetPassword()', $container);
    }
}
