<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE33YP5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE33YP5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE33YP5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE33YP5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE33YP5x\App_KernelDevDebugContainer([
    'container.build_hash' => 'E33YP5x',
    'container.build_id' => '4e657f96',
    'container.build_time' => 1745665240,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE33YP5x');
