<?php

namespace ContainerE33YP5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\HashPasswordListener' shared autowired service.
     *
     * @return \App\EventListener\HashPasswordListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'HashPasswordListener.php';

        return $container->privates['App\\EventListener\\HashPasswordListener'] = new \App\EventListener\HashPasswordListener(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
